# Development override - use caddy.dev.conf instead of caddy.conf
services:
  www:
    volumes:
      - './www:/www'
      - './wwwlogs:/wwwlogs'
      - './caddy.dev.conf:/run/caddy/caddy.conf'
      - './supervisord.conf:/run/supervisor/supervisord.conf'
      - './crontabs.conf:/etc/crontabs/root'
      - './.caddy:/root/.caddy'
    healthcheck:
      test: ["CMD", "true"]
      interval: 30s

